version: "3.8"

services:
  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    environment:
      - SECRET_KEY_BASE=3e242b72dfbabf21ff7a879b2cbf0f3b5722e75b0f048f3817b2f1a93dc9748e44a22f385ecfa894ca97b9929af3a0d83f58376f84789ee213385bf3bf80d4a5
      - BASE_URL=http://localhost:8000
      - DATABASE_URL=postgresql://plausible:plausible@postgres:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://clickhouse:8123/plausible
      - DISABLE_REGISTRATION=true
    ports:
      - "8000:8000"
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:24.12-alpine
    container_name: clickhouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: plausible
      POSTGRES_USER: plausible
      POSTGRES_PASSWORD: plausible
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plausible -d plausible"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "5432:5432"

volumes:
  clickhouse-data:
    driver: local
  clickhouse-logs:
    driver: local
  postgres-data:
    driver: local
